### ISSUE TITLE
Project Checklist

### ISSUE THREAD

**Issue by dbarjs** [elbitdigital/fazendatrevoazul#1]
## Meta:

[Descrição de uma linha] 
## Tarefas:
- [x] Diretório do projeto no Github
- [x] Importação do diretório BASE
- [ ] Arquivo de logo (SVG)
- [ ] Lib. de ícones (Fontello)
- [x] Projeto no Typekit
- [x] Incorporação de configuração do Typekit no index
- [x] Projeto no Firebase
- [x] Configurações de deploy do Firebase
- [x] Configuração do domínio (DNS)
- [x] Projeto no Analytics
- [x] Confirmar propriedade no Google Search Console
- [x] Definição do nome de projeto (GulpFile)
- [x] Definição do nome de projeto (_.js)
- [x] Definição do nome de projeto (_.css)
- [x] Configuração do arquivo package.json
- [x] Construção dos arquivos de distribuição
- [x] Definição de dependências de desenvolvimento (npm)
